/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    'Home copy': typeof import('./src/components/Home copy.vue')['default']
    ICarbonCloudDataOps: typeof import('~icons/carbon/cloud-data-ops')['default']
    ICarbonDownload: typeof import('~icons/carbon/download')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
    IIconParkTwotoneClearFormat: typeof import('~icons/icon-park-twotone/clear-format')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    'Index copy': typeof import('./src/components/Index copy.vue')['default']
    ISystemUiconsSearch: typeof import('~icons/system-uicons/search')['default']
    ISystemUiconsSun: typeof import('~icons/system-uicons/sun')['default']
    ISystemUiconsUndoHistory: typeof import('~icons/system-uicons/undo-history')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMusic: typeof import('./src/components/SearchMusic.vue')['default']
  }
}
